# Generated by Django 5.2.8 on 2025-11-27 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='company_logo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='company_sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='company_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='default_cv',
            field=models.FileField(blank=True, null=True, upload_to='default_cvs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='hiring_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_techs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='remote_policy',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='tech_stack',
            field=models.TextField(blank=True),
        ),
    ]
