# Generated by Django 5.2.8 on 2025-11-27 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationscore',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
    ]
